server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.orm.jpa.JpaTransactionManager: INFO
    org.zalando.logbook: TRACE

spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/antiplagiacode
    username: antiplagiacode
    password: antiplagiacode
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: UTC
    properties:
      hibernate:
        format_sql: true

logbook:
  format:
    style: http