server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.orm.jpa.JpaTransactionManager: INFO
    org.zalando.logbook: INFO

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:antiplagiacode
    driver-class-name: org.h2.Driver
    username: antiplagiacode
    password: antiplagiacode
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
      jdbc:
        time_zone: UTC
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS

logbook:
  format:
    style: http