services:
  main:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      storage-minio:
        condition: service_healthy

  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=antiplagiacode
      - POSTGRES_USER=antiplagiacode
      - POSTGRES_DB=antiplagiacode
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  storage-minio:
    image: minio/minio
    container_name: storage-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: [
        "CMD",
        "curl",
        "-f",
        "http://localhost:9000/minio/health/live"
      ]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s