spring:
  output:
    ansi:
      enabled: ALWAYS
  kafka:
    bootstrap-servers: kafka:29092

logging:
  level:
    org.springframework.web: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.orm.jpa.JpaTransactionManager: INFO
    org.zalando.logbook: TRACE

app:
  antiplagiacode:
    bootstrap-server: http://main:8080
    path:
      download: /api/v1/file/download/{fileId}
  kafka:
    file-scan-topic: file-scan.v1
    group-id: file-scan